const movieInfo = [
  {
    id: 1,
    Title: "Finding Neverland",
    img: "https://i.imgflip.com/3pnmg.jpg",
    date: 3,
    status: "WatchedList",
  },
  {
    id: 2,
    Title: "Spongebob Ight Imma Head Out",
    img: "https://i.imgflip.com/392xtu.jpg",
    date: 2,
    status: "WatchList",
  },
  {
    id: 3,
    Title: "Marked Safe From",
    img: "https://i.imgflip.com/2odckz.jpg",
    date: 2,
    status: "",
  },
  {
    id: 4,
    Title: "Hard To Swallow Pills",
    img: "https://i.imgflip.com/271ps6.jpg",
    date: 2,
    status: "",
  },
  {
    id: 5,
    Title: "Grandma Finds The Internet",
    img: "https://i.imgflip.com/1bhw.jpg",
    date: 2,
    status: "",
  },
  {
    id: 6,
    Title: "Third World Skeptical Kid",
    img: "https://i.imgflip.com/265k.jpg",
    date: 2,
    status: "",
  },
  {
    id: 7,
    Title: "Unsettled Tom",
    img: "https://i.imgflip.com/2wifvo.jpg",
    date: 2,
    status: "",
  },
  {
    id: 8,
    Title: "Evil Kermit",
    img: "https://i.imgflip.com/1e7ql7.jpg",
    date: 2,
    status: "",
  },
  {
    id: 9,
    Title: "Trump Bill Signing",
    img: "https://i.imgflip.com/1ii4oc.jpg",
    date: 2,
    status: "",
  },
  {
    id: 10,
    Title: "Doge",
    img: "https://i.imgflip.com/4t0m5.jpg",
    date: 5,
    status: "",
  },
  {
    id: 11,
    Title: "Leonardo Dicaprio Cheers",
    img: "https://i.imgflip.com/39t1o.jpg",
    date: 2,
    status: "",
  },
  {
    id: 12,
    Title: "Star Wars Yoda",
    img: "https://i.imgflip.com/8k0sa.jpg",
    date: 2,
    status: "",
  },
  {
    id: 13,
    Title: "Success Kid",
    img: "https://i.imgflip.com/1bhk.jpg",
    date: 2,
    status: "",
  },
  {
    id: 14,
    Title: "The Most Interesting Man In The World",
    img: "https://i.imgflip.com/1bh8.jpg",
    date: 2,
    status: "",
  },
  {
    id: 15,
    Title: "That Would Be Great",
    img: "https://i.imgflip.com/c2qn.jpg",
    date: 2,
    status: "",
  },
  {
    id: 16,
    Title: "Brace Yourselves X is Coming",
    img: "https://i.imgflip.com/1bhm.jpg",
    date: 2,
    status: "",
  },
  {
    id: 17,
    Title: "Look At Me",
    img: "https://i.imgflip.com/hmt3v.jpg",
    date: 2,
    status: "",
  },
  {
    id: 18,
    Title: "Jack Sparrow Being Chased",
    img: "https://i.imgflip.com/9vct.jpg",
    date: 2,
    status: "",
  },
  {
    id: 19,
    Title: "Scared Cat",
    img: "https://i.imgflip.com/2hgfw.jpg",
    date: 2,
    status: "",
  },
  {
    id: 20,
    Title: "Bad Luck Brian",
    img: "https://i.imgflip.com/1bip.jpg",
    date: 2,
    status: "",
  },
  {
    id: 21,
    Title: "See Nobody Cares",
    img: "https://i.imgflip.com/3vzej.jpg",
    date: 2,
    status: "",
  },
  {
    id: 22,
    Title: "X All The Y",
    img: "https://i.imgflip.com/1bh9.jpg",
    date: 2,
    status: "",
  },
  {
    id: 23,
    Title: "Imagination Spongebob",
    img: "https://i.imgflip.com/3i7p.jpg",
    date: 2,
    status: "",
  },
  {
    id: 24,
    Title: "Marvel Civil War 1",
    img: "https://i.imgflip.com/govs4.jpg",
    date: 2,
    status: "",
  },
  {
    id: 25,
    Title: "Yo Dawg Heard You",
    img: "https://i.imgflip.com/26hg.jpg",
    date: 2,
    status: "",
  },
  {
    id: 26,
    Title: "First World Problems",
    img: "https://i.imgflip.com/1bhf.jpg",
    date: 2,
    status: "",
  },
  {
    id: 27,
    Title: "Afraid To Ask Andy",
    img: "https://i.imgflip.com/emccr.jpg",
    date: 2,
    status: "",
  },
  {
    id: 28,
    Title: "I Should Buy A Boat Cat",
    img: "https://i.imgflip.com/tau4.jpg",
    date: 2,
    status: "",
  },
  {
    id: 29,
    Title: "Creepy Condescending Wonka",
    img: "https://i.imgflip.com/1bim.jpg",
    date: 2,
    status: "",
  },
  {
    id: 30,
    Title: "Cute Cat",
    img: "https://i.imgflip.com/4xgqu.jpg",
    date: 2,
    status: "",
  },
];

export default movieInfo;
